// Mock Data for Development
// Toggle this flag to switch between mock and real API
export const USE_MOCK_DATA = true;

// Helper to simulate API delay
export const mockDelay = (ms = 800) => 
  new Promise((resolve) => setTimeout(resolve, ms));

// Mock Users Data
export const MOCK_USERS = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'user',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
  },
];

// Mock Auth Response
export const MOCK_AUTH_USER = {
  id: 1,
  name: 'John Doe',
  email: 'john@example.com',
  role: 'admin',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  token: 'mock-jwt-token-12345',
};

// Mock Products Data (example)
export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: 'Product 1',
    price: 99.99,
    description: 'This is product 1',
    image: 'https://via.placeholder.com/300',
  },
  {
    id: 2,
    name: 'Product 2',
    price: 149.99,
    description: 'This is product 2',
    image: 'https://via.placeholder.com/300',
  },
];

// Mock People Directory Data
export const MOCK_PEOPLE = [
  {
    id: 1,
    name: 'Sarah Mitchell',
    company: 'AIA',
    title: 'Product Designer',
    department: 'Product',
    location: 'Los Angeles, CA',
    joinDate: '2026-01-10',
    yearsAtCompany: 5,
    employeeId: '25846245',
    phone: '+1 555-2101',
    email: 'sarah.mitchell@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SarahMitchell',
    isNew: true,
  },
  {
    id: 2,
    name: 'Garrett Crooks',
    company: 'AIA',
    title: 'Product Designer',
    department: 'Product',
    location: 'San Francisco, CA',
    joinDate: '2026-01-10',
    yearsAtCompany: 4,
    employeeId: '25846246',
    phone: '+1 555-2102',
    email: 'garrett.crooks@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=GarrettCrooks',
    isNew: true,
  },
  {
    id: 3,
    name: 'Gust Rath',
    company: 'AIA',
    title: 'Product Designer',
    department: 'Product',
    location: 'San Francisco, CA',
    joinDate: '2026-01-10',
    yearsAtCompany: 3,
    employeeId: '25846247',
    phone: '+1 555-2103',
    email: 'gust.rath@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=GustRath',
    isNew: true,
  },
  {
    id: 4,
    name: 'Stefan Huel',
    company: 'AIA',
    title: 'Product Designer',
    department: 'Product',
    location: 'San Francisco, CA',
    joinDate: '2026-01-10',
    yearsAtCompany: 2,
    employeeId: '25846248',
    phone: '+1 555-2104',
    email: 'stefan.huel@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=StefanHuel',
    isNew: true,
  },
  {
    id: 5,
    name: 'Armando Stark',
    company: 'AIA',
    title: 'Product Designer',
    department: 'Product',
    location: 'San Francisco, CA',
    joinDate: '2026-01-10',
    yearsAtCompany: 6,
    employeeId: '25846249',
    phone: '+1 555-2105',
    email: 'armando.stark@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ArmandoStark',
    isNew: true,
  },
  {
    id: 6,
    name: 'Jace Gibson',
    company: 'VEGA',
    title: 'Product Designer',
    department: 'Product',
    location: 'San Francisco, CA',
    joinDate: '2026-01-10',
    yearsAtCompany: 4,
    employeeId: '25846250',
    phone: '+1 555-2106',
    email: 'jace.gibson@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JaceGibson',
    isNew: false,
  },
  {
    id: 7,
    name: 'Oral Luelwitz',
    company: 'VEGA',
    title: 'Product Designer',
    department: 'Product',
    location: 'San Francisco, CA',
    joinDate: '2026-01-10',
    yearsAtCompany: 1,
    employeeId: '25846251',
    phone: '+1 555-2107',
    email: 'oral.luelwitz@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=OralLuelwitz',
    isNew: false,
  },
  {
    id: 8,
    name: 'Harold Collins',
    company: 'VEGA',
    title: 'Product Designer',
    department: 'Product',
    location: 'San Francisco, CA',
    joinDate: '2026-01-10',
    yearsAtCompany: 3,
    employeeId: '25846252',
    phone: '+1 555-2108',
    email: 'harold.collins@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=HaroldCollins',
    isNew: false,
  },
  {
    id: 9,
    name: 'Maya Patel',
    company: 'AIA',
    title: 'UX Researcher',
    department: 'Design',
    location: 'Austin, TX',
    joinDate: '2025-10-22',
    yearsAtCompany: 2,
    employeeId: '25846253',
    phone: '+1 555-2109',
    email: 'maya.patel@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MayaPatel',
    isNew: false,
  },
  {
    id: 10,
    name: 'Leo Fernandez',
    company: 'VEGA',
    title: 'Engineering Manager',
    department: 'Engineering',
    location: 'New York, NY',
    joinDate: '2024-08-12',
    yearsAtCompany: 7,
    employeeId: '25846254',
    phone: '+1 555-2110',
    email: 'leo.fernandez@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LeoFernandez',
    isNew: false,
  },
  {
    id: 11,
    name: 'Nina Yamaguchi',
    company: 'AIA',
    title: 'People Partner',
    department: 'Human Resources',
    location: 'Seattle, WA',
    joinDate: '2023-05-09',
    yearsAtCompany: 4,
    employeeId: '25846255',
    phone: '+1 555-2111',
    email: 'nina.yamaguchi@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NinaYamaguchi',
    isNew: false,
  },
  {
    id: 12,
    name: 'Ethan Brooks',
    company: 'VEGA',
    title: 'QA Analyst',
    department: 'Quality Assurance',
    location: 'Denver, CO',
    joinDate: '2025-02-19',
    yearsAtCompany: 3,
    employeeId: '25846256',
    phone: '+1 555-2112',
    email: 'ethan.brooks@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=EthanBrooks',
    isNew: false,
  },
];

export const MOCK_RESOURCES = [
  {
    id: 1,
    title: 'Remote Work Policy',
    tag: 'Human Resource',
    description: 'Guidelines for employees working remotely, including eligibility, expectations, and equipment policies.',
    department: 'HR Department',
    date: '2026-01-15',
    type: 'Policy',
    category: 'policies',
  },
  {
    id: 2,
    title: 'Expense Reimbursement Form',
    tag: 'Finance',
    description: 'Form to claim business-related expenses and instructions for submission.',
    department: 'Finance',
    date: '2025-12-01',
    type: 'Form',
    category: 'forms',
  },
  {
    id: 3,
    title: 'Code of Conduct',
    tag: 'Company',
    description: 'Standards and behaviours expected from all employees to maintain a professional workplace.',
    department: 'People & Culture',
    date: '2025-11-20',
    type: 'Policy',
    category: 'policies',
  },
  {
    id: 4,
    title: 'New Starter Checklist',
    tag: 'HR',
    description: 'Checklist for onboarding new hires covering admin, IT access and welcome tasks.',
    department: 'People & Culture',
    date: '2026-02-01',
    type: 'Template',
    category: 'forms',
  },
  {
    id: 5,
    title: 'Flexible Working Guidelines',
    tag: 'Human Resource',
    description: 'Policy outlining flexible working arrangements and approval process.',
    department: 'HR Department',
    date: '2025-10-10',
    type: 'Policy',
    category: 'policies',
  },
  {
    id: 6,
    title: 'Travel Expense Form',
    tag: 'Finance',
    description: 'Form to claim travel expenses and per-diem rates.',
    department: 'Finance',
    date: '2025-09-05',
    type: 'Form',
    category: 'forms',
  },
  {
    id: 7,
    title: 'Data Protection Policy',
    tag: 'Legal',
    description: 'Company rules for handling personal data and compliance responsibilities.',
    department: 'Legal',
    date: '2025-08-12',
    type: 'Policy',
    category: 'policies',
  },
  {
    id: 8,
    title: 'IT Access Request Template',
    tag: 'IT',
    description: 'Template for requesting system access for new hires and role changes.',
    department: 'IT',
    date: '2026-01-20',
    type: 'Template',
    category: 'forms',
  },
  {
    id: 9,
    title: 'Health & Safety Manual',
    tag: 'Operations',
    description: 'Guidance on workplace safety, emergency procedures and reporting incidents.',
    department: 'Operations',
    date: '2024-12-15',
    type: 'Policy',
    category: 'policies',
  },
  {
    id: 10,
    title: 'Performance Review Template',
    tag: 'People',
    description: 'Template used by managers for conducting performance reviews.',
    department: 'People & Culture',
    date: '2025-07-01',
    type: 'Template',
    category: 'forms',
  },
  {
    id: 11,
    title: 'Sick Leave Policy',
    tag: 'HR',
    description: 'Procedures for reporting sick leave and documentation requirements.',
    department: 'HR Department',
    date: '2025-06-18',
    type: 'Policy',
    category: 'policies',
  },
  {
    id: 12,
    title: 'Expense Policy - International Travel',
    tag: 'Finance',
    description: 'Specific rules for international travel and currency reimbursement.',
    department: 'Finance',
    date: '2024-11-02',
    type: 'Policy',
    category: 'policies',
  },
  {
    id: 13,
    title: 'Project Kickoff Checklist',
    tag: 'PMO',
    description: 'Checklist to ensure all stakeholders and technical requirements are ready at project start.',
    department: 'Project Management',
    date: '2025-05-22',
    type: 'Template',
    category: 'forms',
  },
  {
    id: 14,
    title: 'Security Incident Report Form',
    tag: 'Security',
    description: 'Form to report security incidents and steps for escalation.',
    department: 'IT Security',
    date: '2026-01-05',
    type: 'Form',
    category: 'forms',
  },
  {
    id: 15,
    title: 'Equal Opportunity Policy',
    tag: 'People',
    description: 'Company commitment to equal opportunity and non-discrimination.',
    department: 'People & Culture',
    date: '2024-10-01',
    type: 'Policy',
    category: 'policies',
  },
  {
    id: 16,
    title: 'Vendor Onboarding Checklist',
    tag: 'Procurement',
    description: 'Steps and documentation required to onboard third-party vendors.',
    department: 'Procurement',
    date: '2025-03-14',
    type: 'Template',
    category: 'forms',
  },
];

// Add more mock data as needed for different features
// Mock Home Dashboard Data
export const MOCK_HOME_DATA = {
  dashboard: {
    news: [
      {
        id: 1,
        title: 'AIA receives Best Go Green Initiative Award',
        description: 'We are proud to announce that AIA Engineering has been honored with the Best Go Green Initiative Award at the Net Zero Summit and Awards. This award is a recognition of our commitment towards sustainable practices and environmental responsibility.',
        image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
        date: '2025-03-11',
        category: 'Important',
      },
      {
        id: 2,
        title: 'Company Achieves Record Q4 Results',
        description: 'We are thrilled to announce that our company has achieved record-breaking results in Q4 2025, exceeding all expectations.',
        image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
        date: '2026-02-08',
        category: 'Company News',
      },
      {
        id: 3,
        title: 'New Product Launch: Innovation 2026',
        description: 'Introducing our latest innovation that will revolutionize the industry. Join us for the virtual launch event.',
        image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
        date: '2026-02-09',
        category: 'Product',
      },
      {
        id: 4,
        title: 'Team Building Event This Weekend',
        description: 'Join us for an exciting team building retreat. Activities include workshops, outdoor games, and networking.',
        image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800',
        date: '2026-02-10',
        category: 'Events',
      },
    ],
    quickLinks: [
      { id: 1, name: 'Apply Leave', icon: '📅', link: '/leave/apply' },
      { id: 2, name: 'View Payslip', icon: '💰', link: '/payroll/payslip' },
      { id: 3, name: 'Submit Timesheet', icon: '⏰', link: '/timesheet' },
      { id: 4, name: 'IT Support', icon: '💻', link: '/support/it' },
      { id: 5, name: 'Employee Directory', icon: '👥', link: '/people' },
      { id: 6, name: 'Policies', icon: '📋', link: '/policies' },
    ],
    events: [
      {
        id: 1,
        title: 'All Hands Meeting',
        date: '2026-02-15',
        time: '10:00 AM',
        location: 'Conference Hall A',
        attendees: 45,
      },
      {
        id: 2,
        title: 'Tech Talk: AI & ML',
        date: '2026-02-18',
        time: '2:00 PM',
        location: 'Virtual',
        attendees: 120,
      },
      {
        id: 3,
        title: 'Town Hall Q&A',
        date: '2026-02-22',
        time: '11:00 AM',
        location: 'Main Auditorium',
        attendees: 200,
      },
      {
        id: 4,
        title: 'Wellness Workshop',
        date: '2026-02-25',
        time: '4:00 PM',
        location: 'Online',
        attendees: 80,
      },
    ],
    newJoinees: [
      { id: 1, name: 'Sarah Johnson', position: 'Senior Developer', department: 'Engineering', joinDate: '2026-02-01', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah', phone: '+1 555-0101', email: 'sarah.j@company.com' },
      { id: 2, name: 'Michael Chen', position: 'Product Manager', department: 'Product', joinDate: '2026-02-03', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael', phone: '+1 555-0102', email: 'michael.c@company.com' },
      { id: 3, name: 'Emily Davis', position: 'UX Designer', department: 'Design', joinDate: '2026-02-05', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily', phone: '+1 555-0103', email: 'emily.d@company.com' },
      { id: 4, name: 'Rahul Mehta', position: 'Business Analyst', department: 'Strategy', joinDate: '2026-02-07', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul', phone: '+1 555-0104', email: 'rahul.m@company.com' },
      { id: 5, name: 'Jessica Wong', position: 'Data Engineer', department: 'Engineering', joinDate: '2026-02-08', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica', phone: '+1 555-0105', email: 'jessica.w@company.com' },
      { id: 6, name: 'James Wilson', position: 'Marketing Specialist', department: 'Marketing', joinDate: '2026-02-09', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', phone: '+1 555-0106', email: 'james.w@company.com' },
      { id: 7, name: 'Maria Garcia', position: 'HR Coordinator', department: 'Human Resources', joinDate: '2026-02-10', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria', phone: '+1 555-0107', email: 'maria.g@company.com' },
      { id: 8, name: 'Daniel Kim', position: 'Frontend Developer', department: 'Engineering', joinDate: '2026-02-11', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel', phone: '+1 555-0108', email: 'daniel.k@company.com' },
      { id: 9, name: 'Sophie Turner', position: 'Content Writer', department: 'Marketing', joinDate: '2026-02-12', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie', phone: '+1 555-0109', email: 'sophie.t@company.com' },
      { id: 10, name: "Kevin O'Brien", position: 'DevOps Engineer', department: 'Engineering', joinDate: '2026-02-13', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin', phone: '+1 555-0110', email: 'kevin.o@company.com' },
      { id: 11, name: 'Amanda Foster', position: 'Finance Analyst', department: 'Finance', joinDate: '2026-02-14', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda', phone: '+1 555-0111', email: 'amanda.f@company.com' },
      { id: 12, name: 'Chris Lee', position: 'QA Engineer', department: 'Quality Assurance', joinDate: '2026-02-15', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chris', phone: '+1 555-0112', email: 'chris.l@company.com' },
    ],
    courses: [
      {
        id: 1,
        title: 'Advanced JavaScript Patterns',
        instructor: 'John Smith',
        progress: 65,
        totalLessons: 24,
        completedLessons: 15,
        thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400',
        deadline: '2026-03-15',
      },
      {
        id: 2,
        title: 'Leadership & Management',
        instructor: 'Dr. Jane Wilson',
        progress: 40,
        totalLessons: 18,
        completedLessons: 7,
        thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
        deadline: '2026-03-20',
      },
      {
        id: 3,
        title: 'Data Analytics Fundamentals',
        instructor: 'Robert Taylor',
        progress: 85,
        totalLessons: 20,
        completedLessons: 17,
        thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
        deadline: '2026-02-28',
      },
      {
        id: 4,
        title: 'Cloud Architecture & AWS',
        instructor: 'Amy Foster',
        progress: 20,
        totalLessons: 30,
        completedLessons: 6,
        thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
        deadline: '2026-04-10',
      },
      {
        id: 5,
        title: 'Agile & Scrum Master',
        instructor: 'Mark Stevens',
        progress: 55,
        totalLessons: 12,
        completedLessons: 7,
        thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
        deadline: '2026-03-25',
      },
      {
        id: 6,
        title: 'React & Next.js Advanced',
        instructor: 'Sarah Johnson',
        progress: 90,
        totalLessons: 15,
        completedLessons: 14,
        thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400',
        deadline: '2026-03-01',
      },
      {
        id: 7,
        title: 'Cybersecurity Essentials',
        instructor: 'David Park',
        progress: 35,
        totalLessons: 22,
        completedLessons: 8,
        thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400',
        deadline: '2026-04-05',
      },
      {
        id: 8,
        title: 'Communication Skills',
        instructor: 'Lisa Chen',
        progress: 70,
        totalLessons: 10,
        completedLessons: 7,
        thumbnail: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400',
        deadline: '2026-03-12',
      },
    ],
    birthdays: [
      {
        id: 1,
        name: 'Alex Martinez',
        position: 'HR Manager',
        department: 'Human Resources',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        date: '2026-02-10',
      },
      {
        id: 2,
        name: 'Lisa Anderson',
        position: 'Marketing Lead',
        department: 'Marketing',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
        date: '2026-02-10',
      },
      {
        id: 3,
        name: 'Sanjay Patel',
        position: 'Operations Manager',
        department: 'Operations',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sanjay',
        date: '2026-02-10',
      },
      {
        id: 4,
        name: 'Priya Sharma',
        position: 'QA Engineer',
        department: 'Quality Assurance',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
        date: '2026-02-10',
      },
    ],
    anniversaries: [
      {
        id: 1,
        name: 'David Brown',
        position: 'Senior Engineer',
        department: 'Engineering',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
        yearsCompleted: 5,
        joinDate: '2021-02-10',
      },
      {
        id: 2,
        name: 'Rachel Green',
        position: 'Finance Director',
        department: 'Finance',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel',
        yearsCompleted: 3,
        joinDate: '2023-02-10',
      },
      {
        id: 3,
        name: 'Anita Desai',
        position: 'HR Business Partner',
        department: 'Human Resources',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anita',
        yearsCompleted: 2,
        joinDate: '2024-02-10',
      },
    ],
  },
  news: [],
  quickLinks: [],
  events: [],
  newJoinees: [],
  courses: [],
  birthdays: [],
  anniversaries: [],
};
// Mock News Data (Extended)
export const MOCK_NEWS_DATA = [
  {
    id: 1,
    title: 'AIA receives Best Go Green Initiative Award',
    description: 'We are proud to announce that AIA Engineering has been honored with the Best Go Green Initiative Award at the Net Zero Summit and Awards. This award is a recognition of our commitment towards sustainable practices and environmental responsibility.',
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
    date: '2026-03-11',
    category: 'Important',
  },
  {
    id: 2,
    title: 'Company Achieves Record Q4 Results',
    description: 'We are thrilled to announce that our company has achieved record-breaking results in Q4 2025, exceeding all expectations and setting new benchmarks for growth.',
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
    date: '2026-02-08',
    category: 'Company News',
  },
  {
    id: 3,
    title: 'New Product Launch: Innovation 2026',
    description: 'Introducing our latest innovation that will revolutionize the industry. Join us for the virtual launch event on March 15th.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
    date: '2026-02-09',
    category: 'Product',
  },
  {
    id: 4,
    title: 'Team Building Event This Weekend',
    description: 'Join us for an exciting team building retreat. Activities include workshops, outdoor games, and networking opportunities.',
    image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800',
    date: '2026-02-10',
    category: 'Events',
  },
  {
    id: 5,
    title: 'Annual Town Hall Meeting Announced',
    description: 'CEO will address all employees in the upcoming town hall meeting. Topics include company vision, strategic goals, and Q&A session.',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800',
    date: '2026-02-12',
    category: 'Announcements',
  },
  {
    id: 6,
    title: 'Employee Wellness Program Launch',
    description: 'New comprehensive wellness program offers fitness classes, mental health support, and nutrition counseling for all employees.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    date: '2026-02-14',
    category: 'Company News',
  },
  {
    id: 7,
    title: 'Innovation Lab Opens New Facility',
    description: 'State-of-the-art research facility dedicated to developing cutting-edge solutions and fostering innovation.',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800',
    date: '2026-02-16',
    category: 'Product',
  },
  {
    id: 8,
    title: 'Sustainability Report 2025 Released',
    description: 'Our annual sustainability report highlights achievements in reducing carbon footprint and implementing green initiatives.',
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800',
    date: '2026-02-18',
    category: 'Important',
  },
  {
    id: 9,
    title: 'Global Expansion: New Office in Singapore',
    description: 'Expanding our presence in Asia Pacific with a new regional headquarters in Singapore, creating 200+ jobs.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    date: '2026-02-20',
    category: 'Company News',
  },
  {
    id: 10,
    title: 'Tech Conference 2026 Registration Open',
    description: 'Annual technology conference featuring industry leaders, workshops, and networking opportunities. Early bird registration now available.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    date: '2026-02-22',
    category: 'Events',
  },
];